# Generated by Django 4.1.7 on 2023-04-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('prix', models.FloatField()),
                ('quantite', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits')),
            ],
        ),
    ]
