# Generated by Django 4.1.7 on 2023-04-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=256)),
                ('prenom', models.CharField(max_length=256)),
                ('ddn', models.DateField()),
                ('mail', models.EmailField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=256)),
            ],
        ),
    ]
